#!/usr/bin/env bash
#
# by Siddharth Dushantha
#
# CLI program for FF PDF
# https://github.com/sdushantha/ff-pdf
#

STARTPAGE="$HOME/.config/ff-pdf/startpage.html"
PROFILE="FF_PROFILE"

if printf %b "$1" | grep -Eq "(-h|--help)";then
    echo "Usage: ff-pdf FILE"
    exit
fi

# Open STARTPAGE if now file is provided
file_path="${1:-$STARTPAGE}"
if command -v firefox > /dev/null; then 
    firefox --profile "$PROFILE" --new-window "$file_path"
elif command -v librewolf > /dev/null; then 
    librewolf --profile "$PROFILE" --new-window "$file_path"
fi

